//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Opt_Summer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Opt_Summer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 权限问题 .
        ///
        /// 错误信息: {0}
        ///
        ///.
        /// </summary>
        internal static string authorityError1 {
            get {
                return ResourceManager.GetString("authorityError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 详细:
        ///
        ///{0}.
        /// </summary>
        internal static string authorityError2 {
            get {
                return ResourceManager.GetString("authorityError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 输入数据只能为INFINITY或数字.
        /// </summary>
        internal static string InputValueError {
            get {
                return ResourceManager.GetString("InputValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开保存的配置信息.
        /// </summary>
        internal static string loadDataTitle {
            get {
                return ResourceManager.GetString("loadDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 读取失败.
        /// </summary>
        internal static string loadError {
            get {
                return ResourceManager.GetString("loadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存配置数据.
        /// </summary>
        internal static string saveDataTitle {
            get {
                return ResourceManager.GetString("saveDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存完成!.
        /// </summary>
        internal static string saveSucceeded {
            get {
                return ResourceManager.GetString("saveSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本文件 (*.txt)|*.txt.
        /// </summary>
        internal static string textFormat {
            get {
                return ResourceManager.GetString("textFormat", resourceCulture);
            }
        }
    }
}
